[[FFplay]]
arch = "aarch64"
git-tree-sha1 = "b493140ed5f5e505377cfe2ff4f779fba5fa8a61"
os = "macos"

    [[FFplay.download]]
    sha256 = "c911dc12c66a5c50d63759c7dfe609061c94fcaa3855b1f72d724818da038b24"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v8.1.2+0/FFplay.v8.1.2.aarch64-apple-darwin.tar.gz"
[[FFplay]]
arch = "aarch64"
git-tree-sha1 = "c8751800e7d4bbc489e4f7e56920b1d6981543ca"
libc = "glibc"
os = "linux"

    [[FFplay.download]]
    sha256 = "621ad1bf5553dd4c2987d0e266d2744ca6f7d058b07e94a4e4a8f92989bd1e31"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v8.1.2+0/FFplay.v8.1.2.aarch64-linux-gnu.tar.gz"
[[FFplay]]
arch = "aarch64"
git-tree-sha1 = "e9bf6e05e722db90fec3294333a8a2ea53552da9"
libc = "musl"
os = "linux"

    [[FFplay.download]]
    sha256 = "1f226841af6a2e445d573b6fe3a776adf2400ef4917a9d9dbbe0aa298c02cd5d"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v8.1.2+0/FFplay.v8.1.2.aarch64-linux-musl.tar.gz"
[[FFplay]]
arch = "aarch64"
git-tree-sha1 = "e4db816a2d5110c0cd7be38d63212d37dff07374"
os = "freebsd"

    [[FFplay.download]]
    sha256 = "63ad586d350403450e7fafad5ed9e4073ee8d951dc66f23a1a9a6dd4510bf77d"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v8.1.2+0/FFplay.v8.1.2.aarch64-unknown-freebsd.tar.gz"
[[FFplay]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9294b18c55b77c79100a89ae0e2b5dd4f57cce95"
libc = "glibc"
os = "linux"

    [[FFplay.download]]
    sha256 = "8c5f1717158cb92c3358c741b90dfc38b24c08394d91fd512a1cfbcd1db9497d"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v8.1.2+0/FFplay.v8.1.2.armv6l-linux-gnueabihf.tar.gz"
[[FFplay]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9bf4350c19f16b37692013803fcc6d7efd8449a9"
libc = "musl"
os = "linux"

    [[FFplay.download]]
    sha256 = "580553ce6b44ab05d40b322af9734681219620c01b16eefa62044d6308f13227"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v8.1.2+0/FFplay.v8.1.2.armv6l-linux-musleabihf.tar.gz"
[[FFplay]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2f80eedb7ded5957fd4675bab40d0c8feab7ad63"
libc = "glibc"
os = "linux"

    [[FFplay.download]]
    sha256 = "bebaf932aa545e989a65220c56476d83bb76275e068e8c185ac7e90116b8e42b"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v8.1.2+0/FFplay.v8.1.2.armv7l-linux-gnueabihf.tar.gz"
[[FFplay]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ac41b1a6bf6e345e16d3f9d6f4c99c9ddb1c7c25"
libc = "musl"
os = "linux"

    [[FFplay.download]]
    sha256 = "019dd5153135e2e9a0e805ab1086f8a1698cf59ff44951c09e41fabc3d7f41c9"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v8.1.2+0/FFplay.v8.1.2.armv7l-linux-musleabihf.tar.gz"
[[FFplay]]
arch = "i686"
git-tree-sha1 = "b8cd76e0ea4084915003b299e359e9aee66b2fdf"
libc = "glibc"
os = "linux"

    [[FFplay.download]]
    sha256 = "7ca2617e43b65fcca12c3b088c59286198a241ba7eb1c0bac85e7687bd75c02e"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v8.1.2+0/FFplay.v8.1.2.i686-linux-gnu.tar.gz"
[[FFplay]]
arch = "i686"
git-tree-sha1 = "6889548e5b635f4c6ee28d08f3f9166e3be93e53"
libc = "musl"
os = "linux"

    [[FFplay.download]]
    sha256 = "05a3114d3fe93ba9865038dc19987f99eeac7ce5237be2f496f5454d41942a2d"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v8.1.2+0/FFplay.v8.1.2.i686-linux-musl.tar.gz"
[[FFplay]]
arch = "i686"
git-tree-sha1 = "f4f9b3591428479502be4736334f6d4df32675ee"
os = "windows"

    [[FFplay.download]]
    sha256 = "e9f0c023e8ceb0d05572d548d36fee832983c7d2fdc5006e490f9e10d70e0179"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v8.1.2+0/FFplay.v8.1.2.i686-w64-mingw32.tar.gz"
[[FFplay]]
arch = "powerpc64le"
git-tree-sha1 = "78fb67fa3ddfbe95b2d636148c1692d4b524b3db"
libc = "glibc"
os = "linux"

    [[FFplay.download]]
    sha256 = "6a5596c928fe746ca7c1088382ba44410e69cd12ceca39723aeabfc47d5ca94a"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v8.1.2+0/FFplay.v8.1.2.powerpc64le-linux-gnu.tar.gz"
[[FFplay]]
arch = "riscv64"
git-tree-sha1 = "741a5e19c16681cff1ec7801ec21eaf088aace58"
libc = "glibc"
os = "linux"

    [[FFplay.download]]
    sha256 = "fb54ee9c8fe861e4418f90e1c6e58eac7ac4dba3c208ef3feb22a6311f7819d0"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v8.1.2+0/FFplay.v8.1.2.riscv64-linux-gnu.tar.gz"
[[FFplay]]
arch = "x86_64"
git-tree-sha1 = "7997ac16e7e96e06e97e1d1c51cbfb220b684a40"
os = "macos"

    [[FFplay.download]]
    sha256 = "b42d0141dd3bb9c28057a4cde1ea488778314aa336406e9f2076a2bcdd98b75c"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v8.1.2+0/FFplay.v8.1.2.x86_64-apple-darwin.tar.gz"
[[FFplay]]
arch = "x86_64"
git-tree-sha1 = "5342c99d9545f8dbcbbee42e5a74433350e77815"
libc = "glibc"
os = "linux"

    [[FFplay.download]]
    sha256 = "f3b64a3a8410236eff2e5a0e379af71384a489e1864abdbbedbdb698900206f3"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v8.1.2+0/FFplay.v8.1.2.x86_64-linux-gnu.tar.gz"
[[FFplay]]
arch = "x86_64"
git-tree-sha1 = "0d53cd1347f5b231a5d560e3f6e74fc569327f85"
libc = "musl"
os = "linux"

    [[FFplay.download]]
    sha256 = "97e407a130a899d154bf20d01b27e28c80bf0d5c116fa73de12a27c91199bb32"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v8.1.2+0/FFplay.v8.1.2.x86_64-linux-musl.tar.gz"
[[FFplay]]
arch = "x86_64"
git-tree-sha1 = "5b3dfa755603eb35f34517b8716674e2f38c7d65"
os = "freebsd"

    [[FFplay.download]]
    sha256 = "c5c5a9448b89722b155b0e00dc0326507b2e691e6f81c25cbd648291ea11b5ec"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v8.1.2+0/FFplay.v8.1.2.x86_64-unknown-freebsd.tar.gz"
[[FFplay]]
arch = "x86_64"
git-tree-sha1 = "a80f8a9eedabc6d7e190c61bc77521c0322b1482"
os = "windows"

    [[FFplay.download]]
    sha256 = "b498fd0b616ff0032285f3026cd324f4b9943e92545613434fc6c1cae1f428eb"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v8.1.2+0/FFplay.v8.1.2.x86_64-w64-mingw32.tar.gz"
