[[FFplay]]
arch = "aarch64"
git-tree-sha1 = "d37696ab84df569ace42b140b53d1ecf1df9f0e3"
os = "macos"

    [[FFplay.download]]
    sha256 = "468992f923f9f6a3d5571b38d3c6b6d76d6237ed1bc08981cc61212c3bbcaa2c"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v8.1.0+0/FFplay.v8.0.1.aarch64-apple-darwin.tar.gz"
[[FFplay]]
arch = "aarch64"
git-tree-sha1 = "8eb561ef03d1aa697c216f42ed60123ec4cce5ec"
libc = "glibc"
os = "linux"

    [[FFplay.download]]
    sha256 = "dc46515aeb7ce8cd1f7ab231e090739e6d5fdc3ea57cf50924c45c15a91b139f"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v8.1.0+0/FFplay.v8.0.1.aarch64-linux-gnu.tar.gz"
[[FFplay]]
arch = "aarch64"
git-tree-sha1 = "db25b14f038d05ff4c7da5c5f22c6ba0dfa8763a"
libc = "musl"
os = "linux"

    [[FFplay.download]]
    sha256 = "29105ed09f72ca79d670861c863abec876573b590ec718b94c60bd0d19fb504b"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v8.1.0+0/FFplay.v8.0.1.aarch64-linux-musl.tar.gz"
[[FFplay]]
arch = "aarch64"
git-tree-sha1 = "19c428f32181514fb3e6b1595db0a420a2acc14f"
os = "freebsd"

    [[FFplay.download]]
    sha256 = "972aeef9f97759f2a2d679db789b840330e4991b76b660e511cbaf72cd12c686"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v8.1.0+0/FFplay.v8.0.1.aarch64-unknown-freebsd.tar.gz"
[[FFplay]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "181ebd97243a4d7c25cb651029d4ba6e8ccbbdc7"
libc = "glibc"
os = "linux"

    [[FFplay.download]]
    sha256 = "40cdefb8ed08aa5d532bdc48cb09641fa2c6c2bda555c166e4c2201c1bb64298"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v8.1.0+0/FFplay.v8.0.1.armv6l-linux-gnueabihf.tar.gz"
[[FFplay]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7fa666c28014490f36d8b517dced292babe24e84"
libc = "musl"
os = "linux"

    [[FFplay.download]]
    sha256 = "2b03ffe9392a407c295370a0f844f08d19572b3d81c1919ec1ab48516d669b85"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v8.1.0+0/FFplay.v8.0.1.armv6l-linux-musleabihf.tar.gz"
[[FFplay]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c63dcf11111964c88c7d11316b50cb0d1d341a34"
libc = "glibc"
os = "linux"

    [[FFplay.download]]
    sha256 = "575e32be78c637a5c8e0db178e0e05e587d79fd912047de000a65d22d306422c"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v8.1.0+0/FFplay.v8.0.1.armv7l-linux-gnueabihf.tar.gz"
[[FFplay]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c99902c5d0dd6c75d317b831ade21c4605634748"
libc = "musl"
os = "linux"

    [[FFplay.download]]
    sha256 = "b6723a5ce41bc0ceeb5218f937429febe93f95ddeca1f0f6415f8ccb9b6f71c4"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v8.1.0+0/FFplay.v8.0.1.armv7l-linux-musleabihf.tar.gz"
[[FFplay]]
arch = "i686"
git-tree-sha1 = "a9544a47196aac5a76a15d8d1f006841bfbd9c8c"
libc = "glibc"
os = "linux"

    [[FFplay.download]]
    sha256 = "e6b3c28a0f7885ba032320f2b5da4e19c4c820d2fa71402bddf3323ecf34c10b"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v8.1.0+0/FFplay.v8.0.1.i686-linux-gnu.tar.gz"
[[FFplay]]
arch = "i686"
git-tree-sha1 = "841311f5ca2140192008f93f4e4368a11b2ce2ae"
libc = "musl"
os = "linux"

    [[FFplay.download]]
    sha256 = "7167c22aa8781e6bc48cc53f5d81f8a5aefbea7584b15c2e8e63ca1d77daf7a0"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v8.1.0+0/FFplay.v8.0.1.i686-linux-musl.tar.gz"
[[FFplay]]
arch = "i686"
git-tree-sha1 = "1b0da78d1ad882cd8162096ca8e68a94b48e9a03"
os = "windows"

    [[FFplay.download]]
    sha256 = "a8e2665e341d93cd6a8ef6466565f81d3854aaa55f056e50301e4ef83538b16b"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v8.1.0+0/FFplay.v8.0.1.i686-w64-mingw32.tar.gz"
[[FFplay]]
arch = "powerpc64le"
git-tree-sha1 = "a8cd47a155a5e49ebb02996e6eadea191beb9795"
libc = "glibc"
os = "linux"

    [[FFplay.download]]
    sha256 = "c5cacbf96538a660cfe43327a834b48ab90f35c5f0b7dc9574c21aaed6ed590b"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v8.1.0+0/FFplay.v8.0.1.powerpc64le-linux-gnu.tar.gz"
[[FFplay]]
arch = "riscv64"
git-tree-sha1 = "b435952e6551c3d1f946fce338b1020111c10423"
libc = "glibc"
os = "linux"

    [[FFplay.download]]
    sha256 = "b8dacdc33cfedd4e73b521e47c5d859e0d753a2bc84c8c3b2b4c524bcc780a63"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v8.1.0+0/FFplay.v8.0.1.riscv64-linux-gnu.tar.gz"
[[FFplay]]
arch = "x86_64"
git-tree-sha1 = "ce95bfb9a112d1667f714bbae775efdcc2ea61d2"
os = "macos"

    [[FFplay.download]]
    sha256 = "9c9fd363d7eebe95f494b022af2a7e421864d1c8eb9074d50fb456aa49277495"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v8.1.0+0/FFplay.v8.0.1.x86_64-apple-darwin.tar.gz"
[[FFplay]]
arch = "x86_64"
git-tree-sha1 = "c21e7e001458f1c5c737afabf4dd961b78fe4bbd"
libc = "glibc"
os = "linux"

    [[FFplay.download]]
    sha256 = "89192af8aa19befb8a111b0713476603a900c6aecda485321388bdb1771ee058"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v8.1.0+0/FFplay.v8.0.1.x86_64-linux-gnu.tar.gz"
[[FFplay]]
arch = "x86_64"
git-tree-sha1 = "df836096ad9ad47ddda9eda46a35f84fcff23b74"
libc = "musl"
os = "linux"

    [[FFplay.download]]
    sha256 = "896adeaa1001c5bafbcb7b1e0759852888fcbd85f30008bc9cdc28596e57f478"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v8.1.0+0/FFplay.v8.0.1.x86_64-linux-musl.tar.gz"
[[FFplay]]
arch = "x86_64"
git-tree-sha1 = "b44aa9b61e70ac5cda168731709da9ecbd136f31"
os = "freebsd"

    [[FFplay.download]]
    sha256 = "0426488ccf78d95e38b335bcff0bbce6ad97e58a5550a3db51d87cc54032a13d"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v8.1.0+0/FFplay.v8.0.1.x86_64-unknown-freebsd.tar.gz"
[[FFplay]]
arch = "x86_64"
git-tree-sha1 = "681dcbdf500a7817e193a383b86b2f023976bfee"
os = "windows"

    [[FFplay.download]]
    sha256 = "bba03a672354954e2586eb59dbedde3b93d1d0285842c1480b24e81e9cf26ae1"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v8.1.0+0/FFplay.v8.0.1.x86_64-w64-mingw32.tar.gz"
