[[FFplay]]
arch = "aarch64"
git-tree-sha1 = "e40d3f74ef0c21804267dfe5a63e26fb99b8a8d8"
os = "macos"

    [[FFplay.download]]
    sha256 = "746e378be1b458f73213ba1f3e1570ffad1e097569ec1a6d68ffeeda7d5d1ef9"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v9.0.0+0/FFplay.v9.0.0.aarch64-apple-darwin.tar.gz"
[[FFplay]]
arch = "aarch64"
git-tree-sha1 = "e1b975d0f39654fc8ed3e2111e47c9ac326fb349"
libc = "glibc"
os = "linux"

    [[FFplay.download]]
    sha256 = "a99651366bf221e208002e66d2dc7d05a36715a275a333994486c0104016d93e"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v9.0.0+0/FFplay.v9.0.0.aarch64-linux-gnu.tar.gz"
[[FFplay]]
arch = "aarch64"
git-tree-sha1 = "48ddbd0ae50a35488d7d0f11054d09bece96c057"
libc = "musl"
os = "linux"

    [[FFplay.download]]
    sha256 = "a708c701d7a848295d7862fc2ba2da887aad9324f19e40e481a473ee27d21ce9"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v9.0.0+0/FFplay.v9.0.0.aarch64-linux-musl.tar.gz"
[[FFplay]]
arch = "aarch64"
git-tree-sha1 = "c62cd70ad2cd44697581911f7ef298e44d752c6b"
os = "freebsd"

    [[FFplay.download]]
    sha256 = "f8d647ca7975c9aea9b1cb58b8f737e99b90b5f815d8ba7e21343413a617de36"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v9.0.0+0/FFplay.v9.0.0.aarch64-unknown-freebsd.tar.gz"
[[FFplay]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dd9a82e7fba50ccf6534d4b3c52baf61903102e2"
libc = "glibc"
os = "linux"

    [[FFplay.download]]
    sha256 = "529ad14b3abceb84190d10f1a841d9ba6c9a149f30e42a05efef9909ed63b573"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v9.0.0+0/FFplay.v9.0.0.armv6l-linux-gnueabihf.tar.gz"
[[FFplay]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "15acb9e2c14f7cb3513462191e4d4d96c5d4b751"
libc = "musl"
os = "linux"

    [[FFplay.download]]
    sha256 = "52bc11cc8cada8fc17ddaf4e816f0902486e42c63b143ef1e65f4b8d8954fd27"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v9.0.0+0/FFplay.v9.0.0.armv6l-linux-musleabihf.tar.gz"
[[FFplay]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "92af368fd0359f11e0d8ebec631e0355ea9912b6"
libc = "glibc"
os = "linux"

    [[FFplay.download]]
    sha256 = "c0386b00c6d0e3d092e86cfc07bcf7bd4b699f2ae53177fcaa2d97f85f61aa45"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v9.0.0+0/FFplay.v9.0.0.armv7l-linux-gnueabihf.tar.gz"
[[FFplay]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "74d181f833cbc8604b2ed81add2ea429ae762ed3"
libc = "musl"
os = "linux"

    [[FFplay.download]]
    sha256 = "5d0ba8dc6df038a830ebf6d4fec9b5839bbd541dcc7f76566a660c34ced0ea31"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v9.0.0+0/FFplay.v9.0.0.armv7l-linux-musleabihf.tar.gz"
[[FFplay]]
arch = "i686"
git-tree-sha1 = "21fd550c22e2638bc4ab70cef818660f7046fa03"
libc = "glibc"
os = "linux"

    [[FFplay.download]]
    sha256 = "3ed228c3ae2c05c3f481cf4cd69ead214e6c33b6cb1cba8a8aff3a80a17b086b"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v9.0.0+0/FFplay.v9.0.0.i686-linux-gnu.tar.gz"
[[FFplay]]
arch = "i686"
git-tree-sha1 = "7e46b38ca18b87972fe478008cd13721d614a0d8"
libc = "musl"
os = "linux"

    [[FFplay.download]]
    sha256 = "e3c62163177fc49e33e958deb510dd36e6ffb2575b1bd135fe52280410a1fd23"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v9.0.0+0/FFplay.v9.0.0.i686-linux-musl.tar.gz"
[[FFplay]]
arch = "i686"
git-tree-sha1 = "90639fb3d8e423e3c6eb0cc8a560aa786cac8be2"
os = "windows"

    [[FFplay.download]]
    sha256 = "6ea9d8de04e405ba5bd1eb67995cb48aa33e3bd10cf3c2e1d4365c2235d30d1d"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v9.0.0+0/FFplay.v9.0.0.i686-w64-mingw32.tar.gz"
[[FFplay]]
arch = "powerpc64le"
git-tree-sha1 = "41fba977bacfb266e71cb1a9fb537eabcea6f9fc"
libc = "glibc"
os = "linux"

    [[FFplay.download]]
    sha256 = "5dd9d35ed4c50df63fd2b3fb292bb91a186d9226139d2330bd0a1ccc30a72ec3"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v9.0.0+0/FFplay.v9.0.0.powerpc64le-linux-gnu.tar.gz"
[[FFplay]]
arch = "riscv64"
git-tree-sha1 = "ad33448fab43e62df318606292dc6b6094af0e74"
libc = "glibc"
os = "linux"

    [[FFplay.download]]
    sha256 = "7d1c6c3f207073a449a78198b94619acdbbfb556d766ed7028423092c9462dcb"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v9.0.0+0/FFplay.v9.0.0.riscv64-linux-gnu.tar.gz"
[[FFplay]]
arch = "x86_64"
git-tree-sha1 = "c6ecaf362660631d0db3b4b5125ddfd47d1d58c8"
os = "macos"

    [[FFplay.download]]
    sha256 = "b23d92c5a151b3fbccec16e2d4859938f0368aa9a12c5a267ec4cb0bb885fa38"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v9.0.0+0/FFplay.v9.0.0.x86_64-apple-darwin.tar.gz"
[[FFplay]]
arch = "x86_64"
git-tree-sha1 = "c1b79679b12e2f1619f4a7e1756e0516a3beea09"
libc = "glibc"
os = "linux"

    [[FFplay.download]]
    sha256 = "3c5942eb00e4345ad1d347cffd90f775f10a7985215ecbb595e126f67d36e49e"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v9.0.0+0/FFplay.v9.0.0.x86_64-linux-gnu.tar.gz"
[[FFplay]]
arch = "x86_64"
git-tree-sha1 = "b133956acf4213d01f3da780a9e3493e5700eaef"
libc = "musl"
os = "linux"

    [[FFplay.download]]
    sha256 = "12a3041de23cc0302b9d06b10e14ad30d4f5f7e88ebce576cfe4176d3bfae4c7"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v9.0.0+0/FFplay.v9.0.0.x86_64-linux-musl.tar.gz"
[[FFplay]]
arch = "x86_64"
git-tree-sha1 = "7e619827159831219cfa49e84b3bc6f967b4b220"
os = "freebsd"

    [[FFplay.download]]
    sha256 = "866c4add9dbc09a21def8b8eac057dbae16a787bd4c33de1b13dd659471afa54"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v9.0.0+0/FFplay.v9.0.0.x86_64-unknown-freebsd.tar.gz"
[[FFplay]]
arch = "x86_64"
git-tree-sha1 = "a7e5d7f815e07cc99ea95044e6984b0ad48c00b9"
os = "windows"

    [[FFplay.download]]
    sha256 = "0a20ce7a85b67da048a42e2364921650a04d6ab906a570ef812d0706877de4f5"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v9.0.0+0/FFplay.v9.0.0.x86_64-w64-mingw32.tar.gz"
