[[FFplay]]
arch = "aarch64"
git-tree-sha1 = "99be5469f74239b90033698940f0efc699a1ea7c"
libc = "glibc"
os = "linux"

    [[FFplay.download]]
    sha256 = "50838645757fb43ddd2c02e01b5421c74a0b7a1b06a56253b3192fce5db1700a"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v4.4.4+0/FFplay.v4.4.4.aarch64-linux-gnu.tar.gz"
[[FFplay]]
arch = "aarch64"
git-tree-sha1 = "0c09a141f1acbdf320f1d65a4bf5fa94404d58b2"
libc = "musl"
os = "linux"

    [[FFplay.download]]
    sha256 = "6cb032607633fff250bc9708c4bb335aa621167e95434dd4732d08e6a34d74db"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v4.4.4+0/FFplay.v4.4.4.aarch64-linux-musl.tar.gz"
[[FFplay]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f951cb4f65e6574ad06fc12fa54f2d17fcd47c68"
libc = "glibc"
os = "linux"

    [[FFplay.download]]
    sha256 = "b463c1cb4cdc1fa4f42f12d969b1544cfcf1eaffa4ee6982610c85833ad1f62b"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v4.4.4+0/FFplay.v4.4.4.armv7l-linux-gnueabihf.tar.gz"
[[FFplay]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6c7520ede4d89aa6d31a439c43d28a4101511dc1"
libc = "musl"
os = "linux"

    [[FFplay.download]]
    sha256 = "aabb8e2c699e61b0fbd7739517f3a0e65ef850fbb87071d57120e5e75a264b1f"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v4.4.4+0/FFplay.v4.4.4.armv7l-linux-musleabihf.tar.gz"
[[FFplay]]
arch = "i686"
git-tree-sha1 = "8330c87d9e0f11171afdfd619f6b3ca076ccbfe5"
libc = "glibc"
os = "linux"

    [[FFplay.download]]
    sha256 = "4f892cba2390603a0c8197f53c0021352d215c8d257eb6502b02b3016eea3423"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v4.4.4+0/FFplay.v4.4.4.i686-linux-gnu.tar.gz"
[[FFplay]]
arch = "i686"
git-tree-sha1 = "58a5072de1c199fd9a6f7c8f9e606b4a9a9d11b0"
libc = "musl"
os = "linux"

    [[FFplay.download]]
    sha256 = "e9158c9e53f9000dea776da56c9f14224c70a27df57ef54c4e4dc4880d1d7dfd"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v4.4.4+0/FFplay.v4.4.4.i686-linux-musl.tar.gz"
[[FFplay]]
arch = "i686"
git-tree-sha1 = "cc1d03a22bf0f1a3d99706b805000e578f98b302"
os = "windows"

    [[FFplay.download]]
    sha256 = "3110d6bb6b4d449b4c9902323249949fe9cbd27682f3903824a2343d37183fb1"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v4.4.4+0/FFplay.v4.4.4.i686-w64-mingw32.tar.gz"
[[FFplay]]
arch = "powerpc64le"
git-tree-sha1 = "59e383c2122fabf30277c956eb692cff088a7cfd"
libc = "glibc"
os = "linux"

    [[FFplay.download]]
    sha256 = "99ad94b03893494d16122ea1da73a1738cd5508b0a89671b00f4fa3ead45a7ad"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v4.4.4+0/FFplay.v4.4.4.powerpc64le-linux-gnu.tar.gz"
[[FFplay]]
arch = "x86_64"
git-tree-sha1 = "29b31fce6f4c97e8ca5c4caf12ceb98afd44476f"
os = "macos"

    [[FFplay.download]]
    sha256 = "3cd2380506aa0a886a9943bb2c16088d43f4db31ecf794c2e6ec5006d066d726"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v4.4.4+0/FFplay.v4.4.4.x86_64-apple-darwin.tar.gz"
[[FFplay]]
arch = "x86_64"
git-tree-sha1 = "a4f498df20586ed6eceb903e5fb9b20898424f5e"
libc = "glibc"
os = "linux"

    [[FFplay.download]]
    sha256 = "583a7c4edbc60a20fa213161b350c33c7cef3f8734a709b0be191ae86bca175c"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v4.4.4+0/FFplay.v4.4.4.x86_64-linux-gnu.tar.gz"
[[FFplay]]
arch = "x86_64"
git-tree-sha1 = "5d8a0a77dbfcb9ee4ecc5672aeefe8b2c8e0614f"
libc = "musl"
os = "linux"

    [[FFplay.download]]
    sha256 = "e95d2fac3339e65351b4949bb30adad83b1f268f55feaea761e08771ef39a641"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v4.4.4+0/FFplay.v4.4.4.x86_64-linux-musl.tar.gz"
[[FFplay]]
arch = "x86_64"
git-tree-sha1 = "123ea655d13eaf907962b1890441f6213fd69cbc"
os = "freebsd"

    [[FFplay.download]]
    sha256 = "badc9c3247e64ff916ff833879f6234bdfbda186de609e77d5df251e86c285c2"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v4.4.4+0/FFplay.v4.4.4.x86_64-unknown-freebsd.tar.gz"
[[FFplay]]
arch = "x86_64"
git-tree-sha1 = "9a875610f8a04b32b9a105f4c4fc0087081c543d"
os = "windows"

    [[FFplay.download]]
    sha256 = "1e66c18f0c43c2aff8897e0533ba96ef6d59434481d7dd3cbc018a798632d940"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v4.4.4+0/FFplay.v4.4.4.x86_64-w64-mingw32.tar.gz"
