[[FFplay]]
arch = "aarch64"
git-tree-sha1 = "5555fa5b7e9a654e224e285cb01805097bdb54b9"
os = "macos"

    [[FFplay.download]]
    sha256 = "16f1a3152d470667b2c27e7dece8ee7ea12ec7432d69b235c5c7844a1cf1238b"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v7.1.0+0/FFplay.v7.1.0.aarch64-apple-darwin.tar.gz"
[[FFplay]]
arch = "aarch64"
git-tree-sha1 = "8341b5e6f277a8fd2c9ba1429f36ef023825ce98"
libc = "glibc"
os = "linux"

    [[FFplay.download]]
    sha256 = "aefd3cd02100d58a45f356b71ff26aec85623d12c2a3b40e13c39b1a82d9a0a1"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v7.1.0+0/FFplay.v7.1.0.aarch64-linux-gnu.tar.gz"
[[FFplay]]
arch = "aarch64"
git-tree-sha1 = "ebe348ac6c6c9560f393d6ef606eb5d63302f5c8"
libc = "musl"
os = "linux"

    [[FFplay.download]]
    sha256 = "a89dbe669c77c5af18c197749b51ef3dc8098ada8be2a403b2f9330ba766faf2"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v7.1.0+0/FFplay.v7.1.0.aarch64-linux-musl.tar.gz"
[[FFplay]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cf409fc7a2abd78f6d8ef372631fbb8607b3541f"
libc = "glibc"
os = "linux"

    [[FFplay.download]]
    sha256 = "b5935d830175e1482dc1bf0c06a8ad919d741615f6085b4da4ebf83e9c7a99d8"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v7.1.0+0/FFplay.v7.1.0.armv7l-linux-gnueabihf.tar.gz"
[[FFplay]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bfbd2f61a94b61977e1b8d1232044ad9d9d45384"
libc = "musl"
os = "linux"

    [[FFplay.download]]
    sha256 = "961574ef045540effb8c79b3fe7ee83366d0228d06679772c5cf6fca61642f16"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v7.1.0+0/FFplay.v7.1.0.armv7l-linux-musleabihf.tar.gz"
[[FFplay]]
arch = "i686"
git-tree-sha1 = "2503df90d6985f15dca03a2c65a5555ee8738a23"
libc = "glibc"
os = "linux"

    [[FFplay.download]]
    sha256 = "2bf7aecd575e0f9be6b3312f0eb14ae61e494007ae17bb4ff6a69062653df194"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v7.1.0+0/FFplay.v7.1.0.i686-linux-gnu.tar.gz"
[[FFplay]]
arch = "i686"
git-tree-sha1 = "59414a2ae998ce6c5c452dbeae73d623c3581528"
libc = "musl"
os = "linux"

    [[FFplay.download]]
    sha256 = "c8a09b21c4771540cd14ebd01868fdef2588d780cd0327bbd8a2d723551c4429"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v7.1.0+0/FFplay.v7.1.0.i686-linux-musl.tar.gz"
[[FFplay]]
arch = "i686"
git-tree-sha1 = "303ae9812f180a407c3280b9606a6ccc2b5e171e"
os = "windows"

    [[FFplay.download]]
    sha256 = "8be99d606436f0114da45df1602b2ec0554701ea4dae2e7343614589c90cd5ce"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v7.1.0+0/FFplay.v7.1.0.i686-w64-mingw32.tar.gz"
[[FFplay]]
arch = "powerpc64le"
git-tree-sha1 = "a8df4ad0e7c2b5b22a6549a3100bd486a1f25374"
libc = "glibc"
os = "linux"

    [[FFplay.download]]
    sha256 = "8cbad6fe0888d52867d83d67b4b41e47ba8e12b834b1b7f28704415850bfb624"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v7.1.0+0/FFplay.v7.1.0.powerpc64le-linux-gnu.tar.gz"
[[FFplay]]
arch = "x86_64"
git-tree-sha1 = "bc2a737f0f512f85e39d6f52e3d167e05753c145"
os = "macos"

    [[FFplay.download]]
    sha256 = "155dcbd45d563464f05acf4b7195c67c0f02b1570b87cafb5c1d6f5610660bbe"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v7.1.0+0/FFplay.v7.1.0.x86_64-apple-darwin.tar.gz"
[[FFplay]]
arch = "x86_64"
git-tree-sha1 = "d89ccc2c1c868fb2514bb1168150bda4b8e5dc48"
libc = "glibc"
os = "linux"

    [[FFplay.download]]
    sha256 = "06eb5e81ae7b2e422e06ac906b3c19560c01ac0f7dcfa824ec9f61b76aca7a74"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v7.1.0+0/FFplay.v7.1.0.x86_64-linux-gnu.tar.gz"
[[FFplay]]
arch = "x86_64"
git-tree-sha1 = "3396845c11820c30a364b40a96445a7626e65ecd"
libc = "musl"
os = "linux"

    [[FFplay.download]]
    sha256 = "1d9f5abede6787f1a33eba0286026f5b9f0559134e02c712577ceb40b048f59c"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v7.1.0+0/FFplay.v7.1.0.x86_64-linux-musl.tar.gz"
[[FFplay]]
arch = "x86_64"
git-tree-sha1 = "3c3cf1321562cddd92fbb6b1d36a0ae6d48417f7"
os = "freebsd"

    [[FFplay.download]]
    sha256 = "50f3c63aab0dff924cce0f80b163a2cd2386e6d5cfc9ad5e19690be57a1bb875"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v7.1.0+0/FFplay.v7.1.0.x86_64-unknown-freebsd.tar.gz"
[[FFplay]]
arch = "x86_64"
git-tree-sha1 = "adeb5a56348138ae84cce38d545c3102a84dc71e"
os = "windows"

    [[FFplay.download]]
    sha256 = "1afbe4d74c191bc398a22775337577c35787f608775f3be335049615b1296f39"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v7.1.0+0/FFplay.v7.1.0.x86_64-w64-mingw32.tar.gz"
