[[FFplay]]
arch = "aarch64"
git-tree-sha1 = "dfafbe3bbe215394e241d456dc41fb94f7dd53b7"
os = "macos"

    [[FFplay.download]]
    sha256 = "1c88c2e75ecf09ae0eed208c7a641dbf55cf9a362dc0b2800a50d2cb3d4ceb6b"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v6.1.1+0/FFplay.v6.1.1.aarch64-apple-darwin.tar.gz"
[[FFplay]]
arch = "aarch64"
git-tree-sha1 = "27ccb1d954f503bee861df818e4ce9f4be1d288e"
libc = "glibc"
os = "linux"

    [[FFplay.download]]
    sha256 = "8efa9c8c892b4bdfd2045a7e9ea40b226bed9f773767774eeb2a7de9cb0d83c6"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v6.1.1+0/FFplay.v6.1.1.aarch64-linux-gnu.tar.gz"
[[FFplay]]
arch = "aarch64"
git-tree-sha1 = "1196756809d09d6412c992ddcd27f3e815df9ee1"
libc = "musl"
os = "linux"

    [[FFplay.download]]
    sha256 = "d1667a51da0d30d1d29769f03b5f54fa2bb8f317ba1c0a4c534f939e826882d6"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v6.1.1+0/FFplay.v6.1.1.aarch64-linux-musl.tar.gz"
[[FFplay]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "46c95dc22a98a98ebdd945f93296260fda5efd25"
libc = "glibc"
os = "linux"

    [[FFplay.download]]
    sha256 = "e4c5f18e697d415c128ea715776cce1c16aeb1e21b50a67dd28e12af33b49d30"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v6.1.1+0/FFplay.v6.1.1.armv7l-linux-gnueabihf.tar.gz"
[[FFplay]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "88626ec0fa525bfad65632b24c935e23c3dab76c"
libc = "musl"
os = "linux"

    [[FFplay.download]]
    sha256 = "f8aaa5479494513b94c72ca55fddbb4ce5d2068a3f52a65e03818b6159e62e02"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v6.1.1+0/FFplay.v6.1.1.armv7l-linux-musleabihf.tar.gz"
[[FFplay]]
arch = "i686"
git-tree-sha1 = "b9ba392cf46a5f83e78ec6b1e4d83b0d4d832941"
libc = "glibc"
os = "linux"

    [[FFplay.download]]
    sha256 = "1a446fbc76923676b0be03cf523bc0497fe560b8a3b507fa555b1fea4e5552a5"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v6.1.1+0/FFplay.v6.1.1.i686-linux-gnu.tar.gz"
[[FFplay]]
arch = "i686"
git-tree-sha1 = "925f4c66c5670207de3b1880e1927e1f4d816d51"
libc = "musl"
os = "linux"

    [[FFplay.download]]
    sha256 = "080aefc84976632289e484f7d14b0b8651ecc3405afb080ee738c4847fca08dd"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v6.1.1+0/FFplay.v6.1.1.i686-linux-musl.tar.gz"
[[FFplay]]
arch = "i686"
git-tree-sha1 = "f88acd797144ca604c97b2002f974f67b6cff98b"
os = "windows"

    [[FFplay.download]]
    sha256 = "4dda16973d08d3d31e4e17cb620298eaf46727f25bb70fc8718e9e3e18864b58"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v6.1.1+0/FFplay.v6.1.1.i686-w64-mingw32.tar.gz"
[[FFplay]]
arch = "powerpc64le"
git-tree-sha1 = "9a51d38bbab4cbf4d9b2c3feb835688c9a512249"
libc = "glibc"
os = "linux"

    [[FFplay.download]]
    sha256 = "ceb989de51eb0893e9a64bda8e83cabed435fddcd3982ff8fe2a9298a5c9509a"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v6.1.1+0/FFplay.v6.1.1.powerpc64le-linux-gnu.tar.gz"
[[FFplay]]
arch = "x86_64"
git-tree-sha1 = "5e8e3ae0cb4c3ad30509b3aba2bfa6177ecb8290"
os = "macos"

    [[FFplay.download]]
    sha256 = "fd979fd9c7a357a03e10b753480e57db1db925d82828626070b8806776f0a9e5"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v6.1.1+0/FFplay.v6.1.1.x86_64-apple-darwin.tar.gz"
[[FFplay]]
arch = "x86_64"
git-tree-sha1 = "e228e7339c8620facde3f57d2b3a60ea17419f88"
libc = "glibc"
os = "linux"

    [[FFplay.download]]
    sha256 = "efb2eed01f860134872e531dd07bd29b36da0a818dcad84d64adb7578ae51fba"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v6.1.1+0/FFplay.v6.1.1.x86_64-linux-gnu.tar.gz"
[[FFplay]]
arch = "x86_64"
git-tree-sha1 = "280883f4a595f896402a002df651f425481321d3"
libc = "musl"
os = "linux"

    [[FFplay.download]]
    sha256 = "7c435bcf52ee7d2760669be41697d3a45935b56cb0008e29a694bd16a9e961b8"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v6.1.1+0/FFplay.v6.1.1.x86_64-linux-musl.tar.gz"
[[FFplay]]
arch = "x86_64"
git-tree-sha1 = "222dc38ff70b2b66c2c952dca5bebe01ae62a23c"
os = "freebsd"

    [[FFplay.download]]
    sha256 = "3aa8c0c54b38cb982f96fc1c62a117f8fa450d7c72c3221556aa4b5606aeef5d"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v6.1.1+0/FFplay.v6.1.1.x86_64-unknown-freebsd.tar.gz"
[[FFplay]]
arch = "x86_64"
git-tree-sha1 = "da07ff1c0ac305fdfc35788a805069899c412b18"
os = "windows"

    [[FFplay.download]]
    sha256 = "ad9e5427bd0eb0851652bede7b2b213106fdf7b2872586a72ffa5ad5fe3ccf76"
    url = "https://github.com/JuliaBinaryWrappers/FFplay_jll.jl/releases/download/FFplay-v6.1.1+0/FFplay.v6.1.1.x86_64-w64-mingw32.tar.gz"
